version: '2'

services:
  app:
    build: app/
    ports:
      - "80:8080"
    links:
      - redis

  redis:
    image: redis
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data

  test:
    build: test/
    links:
      - app

volumes:
  redis-data:
    driver: local
