#!/bin/bash

set -e

/home/travis/google-cloud-sdk/bin/gcloud auth activate-service-account --key-file client-secret.json
/home/travis/google-cloud-sdk/bin/gcloud config set project $PROJECT_NAME
/home/travis/google-cloud-sdk/bin/gcloud --quiet config set container/cluster $CLUSTER_NAME
/home/travis/google-cloud-sdk/bin/gcloud config set compute/zone $CLOUDSDK_COMPUTE_ZONE
/home/travis/google-cloud-sdk/bin/gcloud --quiet container clusters get-credentials $CLUSTER_NAME

/home/travis/google-cloud-sdk/bin/kubectl cluster-info
