#!/bin/bash

set -e

/home/travis/google-cloud-sdk/bin/kubectl config set-credentials default --username=${GKE_USERNAME} --password=${GKE_PASSWORD}
/home/travis/google-cloud-sdk/bin/kubectl config set-cluster default --server=${GKE_SERVER} --insecure-skip-tls-verify=true
/home/travis/google-cloud-sdk/bin/kubectl config set-context default --cluster=default --user=default
/home/travis/google-cloud-sdk/bin/kubectl config use-context default

/home/travis/google-cloud-sdk/bin/kubectl cluster-info
